### ISSUE TITLE
Incorrectly claims that Combat Training overwrites BaseBullet, BaseProjectileNeolithic

### ISSUE THREAD

**Issue by Kriil** [RimWorld-CCL-Reborn/AllYourBase#1]
I only put the following thing defs:
```

 <ThingDef ParentName="BaseHumanMakeableGun">
    <defName>Gun_TrainingBBGun</defName>.......

  <ThingDef ParentName="BaseBullet">
    <defName>Bullet_TrainingBBGun</defName>......

  <ThingDef ParentName="BaseMeleeWeapon_Sharp_Quality">
		<defName>MeleeWeapon_TrainingKnife</defName>......
```

There are no vanilla base abstracts in any files.

**Comment by Mehni** [comment]
It logs the filename and location, where does it find them?

Hugslib log would help here.

**Comment by Mehni** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1542761308&searchtext=Combat+Training 

Is that the mod in question?

`[Combat Training] causes compatibility errors by overwriting BaseProjectileNeolithic in file C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\1542761308\Defs\ThingDefs_Misc\Weapons\BaseTrainingWeapons.xml`

`[Combat Training] causes compatibility errors by overwriting BaseBullet in file C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\1542761308\Defs\ThingDefs_Misc\Weapons\BaseTrainingWeapons.xml`

Line 106 and 39 respectively. The mod clearly includes these Abstract Defs.

https://github.com/Kriil/rimworld-combat-training/blob/dff9a20d40ba6792ad88dff21f0d1c298f1c291e/Defs/ThingDefs_Misc/Weapons/BaseTrainingWeapons.xml#L39-L50

https://github.com/Kriil/rimworld-combat-training/blob/dff9a20d40ba6792ad88dff21f0d1c298f1c291e/Defs/ThingDefs_Misc/Weapons/BaseTrainingWeapons.xml#L106-L117


P.S. what's with `rimworld-combat-training/Program Files (x86)/Steam/steamapps/common/RimWorld/Mods/CombatTraining/Assemblies/` ?

**Comment by Kriil** [comment]
wow. that's weird. That's not what I see in my project. Must have loaded
the wrong files some how.  Thanks!
